blank_issues_enabled: true
contact_links:
    - name: hardhat-polkadot plugins documentation page
      url: https://docs.polkadot.com/develop/smart-contracts/dev-environments/hardhat/
      about: Please refer to the documentation for immediate answers.
