name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    strategy:
      matrix:
        # Disabled windows because it's too slow
        os: [macos-latest, ubuntu-latest]
        node: ["18"]  
    name: Run tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Run tests
        run: |
          cd tests
          chmod +x run.sh
          ./run.sh
        shell: bash
  
  check-tarballs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build
          
      - name: Pack hardhat-polkadot-resolc
        run: pnpm pack
        working-directory: "./packages/hardhat-polkadot-resolc"

      - name: Pack hardhat-polkadot-node
        run: pnpm pack
        working-directory: "./packages/hardhat-polkadot-node"

      - name: Pack hardhat-polkadot
        run: pnpm pack
        working-directory: "./packages/hardhat-polkadot"

      - name: Move to one single folder
        run: |
          mkdir -p packs
          cp ./packages/hardhat-polkadot-resolc/*.tgz packs/
          cp ./packages/hardhat-polkadot-node/*.tgz packs/
          cp ./packages/hardhat-polkadot/*.tgz packs/
          ls -ltr packs

      - name: Check tarballs
        run: |
          cd tests
          chmod +x check-tarballs.sh
          ./check-tarballs.sh ../packs/*.tgz
        shell: bash